Force removal of aws-cli in GitHub runner.
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/aws
Target /usr/local/bin/aws
already exists. You may want to remove it:
  rm '/usr/local/bin/aws'

To force the link and overwrite all conflicting files:
  brew link --overwrite awscli

To list all files that would be deleted:
  brew link --overwrite --dry-run awscli

Possible conflicting files are:
/usr/local/bin/aws -> /usr/local/aws-cli/aws
/usr/local/bin/aws_completer -> /usr/local/aws-cli/aws_completer